#!/usr/bin/env sh
# MAIN REASON TO USE THIS SCRIPT INSTEAD OF `yarn lint:fix`, FACT THAT HERE WE HANDLE ONLY COMMITTED FILES RATHER THEN WHOLE REPOSITORY

# Disable hook at CI
[ -n "$CI" ] && exit 0

. "$(dirname -- "$0")/_/husky.sh"

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Prettify all selected files
echo "$FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write

# Eslint all selected files
echo "$FILES" | xargs ./node_modules/.bin/eslint --fix

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0
